### ISSUE TITLE
Mod causing crashes on Linux

### ISSUE THREAD

**Issue by ghost** [offyerrocker/PD2-AdvancedCrosshairs#5]
It crashes when the startup video starts playing (when the "Loading..." part is done). I tried redownloading the mod in case that would help but it didn't. I attached a .7z with all the mods listed above if that makes it easier. List of mods (from /mods):
AkimboFiremodeToggle
BeardLib
Better Assault Indicator
Borderless Windowed Updated
ColorPicker
CustomFOV
DisableFog
Drag and Drop Inventory
HoldTheKey
Intimidated Outlines
introcinematics121h1
InvertedFlashbangGlare
Lobby Player Info
Low Violence Mode
Lower Shadow map Mod
Message sound
More Weapon Stats
No Dirt Camera
No Flashlight Glow
No more Ads
No Prints
PD2-AdvancedCrosshairs (duh)
PD2-Dynamic-Crosshairs-Enhanced (tried launching without this one but still crashes)

Also using a bunch of mod_overrides mods but it doesn't seem like they would cause a problem...

I'm using the native linux payday 2 version from steam. (native here means "made for linux" basically)
Linux Distro: Arch Linux

[a.zip](https://github.com/offyerrocker/PD2-AdvancedCrosshairs/files/7385051/a.zip)

**Comment by offyerrocker** [comment]
Thanks for the report- I think I know what the problem is.
I believe I accidentally used an asset loading function that only exists in the Windows version instead of the one in SuperBLT's Linux version; I'll confirm and fix ASAP.

**Comment by ghost** [comment]
Ok, I'm gonna wait for a bit to test it rn else I'll test it tomorrow if it's ready (no hurry).

**Comment by offyerrocker** [comment]
Should be fixed now as of commit 7ddf74f. Download it from GitHub and see if that allows you to launch. If not, it might be helpful to share your crashlog.

**Comment by ghost** [comment]
Mod is still causing crashes, i tried clearing the saves folder of every ACH thing there and it still crashed but managed to generate saves/AdvancedCrosshair.txt (i attached the AdvancedCrosshair.txt). However it did not generate the "ACH Addons" folder in saves/.

I am not sure how to find a crash log but i guess it's supposed to be together with renderer_settings.xml and named "crash.txt" but i did not have a crash.txt there. I found a %date%_log.txt file in mods/logs/ i removed it, and launched a game without other mods (with Beardlib tho) and a cleared saves/ folder (i did not remove the blt stuff from saves/). The %date%_log.txt file got generated (inside mods/logs/) but it was empty.


AdvancedCrosshair.txt](https://github.com/offyerrocker/PD2-AdvancedCrosshairs/files/7391858/AdvancedCrosshair.txt)

**Comment by ghost** [comment]
It launched with ach (and all other mods) enabled successfully once, but once i opened "Better Assault Indicator" settings, it crashed. 
I tried then to launch without ach, it launched successfully, checked the same settings and it didn't crash, then launched again with ach enabled and it crashed the same way it did before. Hope this helps.

**Comment by offyerrocker** [comment]
Hmm, so it crashed with BAI installed but worked without? This bears further testing. The game consistently launch without crashing with ACH installed, without BAI? Or with ACH and no other mods (except for SBLT and BeardLib)?

**Comment by ghost** [comment]
It basically always crashes, the only time it worked was with all other mods installed, but it crashed as soon as I opened BAI settings. As far as i know there is not something special I did, in fact I didn't even touch payday 2 since the last time I did some tests for this issue. It just worked randomly once. I have no idea how to reproduce it.

**Comment by Banacizo** [comment]
My Issue has the exact same symptoms so I'm writing in this issue instead of a new one. The game crashes after the black "Loading..." screen, though I do get a couple of seconds of the intro video now and then.
My other mods are:
- BeardLib
- PocoHud 3
- HoloInfo
- Lobby Player Info
- Real Weapon Names
- Translucent Briefing GUI
- Throwables in team loadout

I did run the game with extra logs and heres the relevant section:
```
07:03:24 PM Lua: [INFO] [Keybind] Registered keybind [BLTKeybind achievement_toggle] 
07:03:24 PM Lua: [INFO] [BLT] Setting up mod:  PocoHud3 
07:03:24 PM Lua: [INFO] [BLT] Setting up mod:  Lobby Player Info 
07:03:29 PM Lua: RWN: Current language is: en
07:03:29 PM Lua: [AdvancedCrosshair] MenuManagerInitialize begin
07:03:29 PM Lua: [AdvancedCrosshair] MenuManagerInitialize complete
07:03:29 PM Lua: [AdvancedCrosshair] MenuManagerPopulateCustomMenus begin
07:03:29 PM Lua: [AdvancedCrosshair] Loading addons...
07:03:29 PM Lua: [AdvancedCrosshair] Addon loading complete.
07:03:29 PM Lua: [AdvancedCrosshair] Populating hitmarker menus...
07:03:29 PM Lua: [AdvancedCrosshair] Populating customization_menus...
07:03:29 PM Lua: [AdvancedCrosshair] Populating crosshair menus...
07:03:29 PM Lua: [AdvancedCrosshair] Populating general crosshair menu...
07:03:29 PM Lua: [AdvancedCrosshair] Populating hitsound menus...
07:03:29 PM Lua: [AdvancedCrosshair] MenuManagerPopulateCustomMenus complete
07:03:29 PM Lua: [AdvancedCrosshair] MenuManagerBuildCustomMenus begin
07:03:29 PM Lua: [AdvancedCrosshair] Building customization menu...
07:03:29 PM Lua: [AdvancedCrosshair] MenuManagerBuildCustomMenus complete
07:03:30 PM Log:  (/home/banacizo/.local/share/Steam/steamapps/common/PAYDAY 2/makening/payday2-superblt/src/http/http.cpp:51) CURL_INITD
07:03:30 PM Lua: Poco:Init
07:03:30 PM Lua: Locale EN loaded
07:03:30 PM FATAL ERROR:  (/home/banacizo/.local/share/Steam/steamapps/common/PAYDAY 2/makening/payday2-superblt/platforms/linux/src/log.cpp:27) Fatal Error, Aborting: Segmentation fault!

Obtained 19 C++ stack frames:
 0x7fceac14c28b libsuperblt_loader.so : blt::error::handler(int)+0x8b
 0x7fceab910210 libc.so.6 : +0x46210
                payday2_release() [0x5bb049]
                payday2_release() [0x465a75]
                payday2_release() [0x5699a4]
                payday2_release() [0xf46a58]
                payday2_release() [0xf4d40b]
                payday2_release() [0xf4d7c5]
                payday2_release() [0xf63978]
                payday2_release() [0x56b073]
                payday2_release() [0x992393]
 0x7fceac0e7339 libsuperblt_loader.so : blt::dt_Application_update(void*)+0x69
                payday2_release() [0x991b6f]
                payday2_release() [0xa4dbbc]
                payday2_release() [0xa4eb25]
                payday2_release() [0xa4d834]
 0x7fceab8f10b3 libc.so.6 : __libc_start_main+0xf3
                payday2_release() [0x421394]


07:03:30 PM FATAL ERROR:  (/home/banacizo/.local/share/Steam/steamapps/common/PAYDAY 2/makening/payday2-superblt/platforms/linux/src/log.cpp:27) Thread Lua state:

07:03:30 PM FATAL ERROR:  (/home/banacizo/.local/share/Steam/steamapps/common/PAYDAY 2/makening/payday2-superblt/platforms/linux/src/log.cpp:27) stack traceback:
```
The "fatal error segmentation fault" line appears if you exit the game via "Exit" in the main menu (not alt f4) or if you crash it with this mod.
Ill also mention here that my game also crashes with Enhanced Hitmarkers after stating that it's copying a .png.

**Comment by offyerrocker** [comment]
Interesting. There doesn't seem to be any conflict on the Lua-side of ACH so far. Perhaps it's an error with one of BeardLib's modules? I've made a few changes to the linux branch; pull them and see what we get this time.

**Comment by Banacizo** [comment]
Here is the log in full:
[2021_12_29_log.txt](https://github.com/offyerrocker/PD2-AdvancedCrosshairs/files/7788390/2021_12_29_log.txt)
Here is the fresh crash.txt
[crash.txt](https://github.com/offyerrocker/PD2-AdvancedCrosshairs/files/7788401/crash.txt)
And here for comparison is log for me opening the game without ACH, loading into main menu and then exiting through "Exit".
[2021_12_29_NO_CRASH_log.txt](https://github.com/offyerrocker/PD2-AdvancedCrosshairs/files/7788419/2021_12_29_NO_CRASH_log.txt)

Is it possible to make a hyper minimalistic version of the mod? Like a script that has no menus or functionality but just loads in an asset similar to how the full mod would do it. Then we can see if that passes launch.

I believe I didnt mention it but im using native Payday - no proton. Using Zorin OS 16 (Ubuntu).

Here is something else though: couple of month ago when I was trying to mod Payday on Linux for the first time BLT was throwing an error and I ended up installing a branch of superBLT that has it fixed. I dug around and I think here is the relevant thread on GitLab: https://gitlab.com/znixian/payday2-superblt/-/issues/81
It does contain the words "image parser", but I dont know how useful that thread is and I havent read too much into it.

**Comment by offyerrocker** [comment]
A lot of the mod is already disabled- all of the assets normally loaded through BeardLib's AddFiles module are disabled, as are the AssetUpdates and Localization BeardLib modules, so it's actually crashing right now without even having loaded any assets. 
I'll have to cast an even wider net with the logs and disabling more functions; try the new commit, and post the logs as before. Your strategy is sound, though, and it's roughly what I'm doing- disabling things til it launches without crashing, and once we get there, I'll re-enable things until we find the pea in the mattress, so to speak.

For the sake of testing, could I also ask you to disable your other mods (except for SuperBLT basemod and BeardLib) when trying to reproduce the crash? There _shouldn't_ be any issues with other mods, but I'm getting a very vague report of incompatibility with PocoHUD from another user, so I want to make sure that the problem is really actually just ACH and not a compatibility problem. 

That thread you've linked is interesting, and may be relevant, but since both you and the original poster of this thread are reporting this issue specifically with ACH and not with other mods, I'd like to rule out the problem being some dumb mistake on my end first.

**Comment by Banacizo** [comment]
One log for no mods coming up:
[2021_12_30_log.txt](https://github.com/offyerrocker/PD2-AdvancedCrosshairs/files/7790802/2021_12_30_log.txt)
The game launched! I have ran the test several times and the results are: it once crashed on clicking "BLT mods", crashed once somewhere in BeardLib menus and 2 times back to back I have been able to launch the game, look at ACH in mod updater UI and exit the game through the menu button (thats the case in the log). I have also once started a Bank: Cash heist and there was no crash.
I double checked v19 with no other mods installed and it crashed at the usual spot.

**Comment by offyerrocker** [comment]
Alright, progress! 
Now that we've narrowed it down a bit more, I've re-enabled the main functionality of the mod. Try it now; if it crashes, we should have some more useful information in the BLT log.

**Comment by Banacizo** [comment]
Good news! Game launched, AND THE MOD WORKS!
Well, almost. Game crashed several times on clicking "BLT mods", ACH options dont appear there. Game crashed several times on clicking "Back" in different menus, including contract purchasing menu.
Mod works in-game, shows hitmarkers. Crosshair didnt appear until I aimed (rmb) for the first time, then wouldnt go away even when aiming. It did bloom properly though.
I didnt clean the log for only one session this time, so it should reflect several different crashes and performance during gameplay:
[2021_12_31_log.txt](https://github.com/offyerrocker/PD2-AdvancedCrosshairs/files/7796275/2021_12_31_log.txt)
Good going so far I say.

**Comment by offyerrocker** [comment]
Innnteresting. So it only crashed when going into the menu, and the only bugged in-heist behaviour was the crosshair not appearing/disappearing correctly according to ADS? 
I'm not certain, but it appears to be related to BeardLib after all. (These crashes in the menus didn't happen with just BeardLib, right?) I'm wondering where the PNG parsing could be coming from since you don't have any addons at all, much less any that are .png format, and the mod icon .png shouldn't be used or showing either. I don't have a new version to test yet, but I should soon.

**Comment by Banacizo** [comment]
Dumb of me to not try it previously but It does crash about 50% of the time on "BLT mods" and always on "Custom achievements" even with no other mods. I was not able to replicate crashes in other menus so lets attribute it to beardlib for now. Yes the mod did seem to work except there were no options for it in "mod options". 
As for the pngs - there are icons for BeardLib and BLT (mods/base/blt.png) in the in-game mod manager so its probably those.

**Comment by greembow** [comment]
Also having issues with this on archlinux, it seems like no other crosshair mods work either... Sometimes it will crash on startup, other times when I load into a game. So far I haven't had a sucessful run. I'll keep you updated with logs if I can get anything.

**Comment by greembow** [comment]
Nevermind, I'm the biggest dumb to ever dumb... I didn't have beardlib for some reason...
